### ISSUE TITLE
Please use a (SPDX-) valid license

### ISSUE THREAD

**Issue by optikfluffel** [CoderDojo/cp-dojos-service#211]
Hi :)

npm just warned me:

```
npm WARN package.json dojos-service@0.0.1 license should be a valid SPDX license expression
```

There are quite a few on [that list](https://spdx.org/licenses/). Do you know which one would be yours?

**Comment by sudheesh001** [comment]
@david-cahill It looks like `cp-dojos-service` is using the MIT license, So changing the `  "license": "BSD",` to MIT should fix this issue.

I am just getting started with cp-dojos-service and I'll be sending a pull request to fix this.

**Comment by tangentfairy** [comment]
That's great thanks @sudheesh001 !
